name: github_trending
description: A library to get GitHub trending repositories and developers, with languages and period options.
version: 1.1.0
homepage: https://github.com/git-touch/github-trending

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.0

dev_dependencies:
  test: ^1.16.5
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
