targets:
  $default:
    builders:
      ferry_generator:graphql_builder:
        enabled: true
        options:
          schema: gql_gitlab|lib/schema.graphql
          output_dir: ""
      ferry_generator:serializer_builder:
        enabled: true
        options:
          schema: gql_gitlab|lib/schema.graphql
          output_dir: ""
