targets:
  $default:
    builders:
      ferry_generator:graphql_builder:
        enabled: true
        options:
          schema: gql_github|lib/schema.graphql
          output_dir: ""
          type_overrides:
            DateTime:
              name: DateTime
            URI:
              name: String
            GitObjectID:
              name: String
      ferry_generator:serializer_builder:
        enabled: true
        options:
          schema: gql_github|lib/schema.graphql
          output_dir: ""
          custom_serializers:
            - import: package:gql_github/utils/date_time_serializer.dart
              name: DateTimeSerializer
